-- Create Education Categories Table
create table if not exists public.education_categories (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Education Questions Table
create table if not exists public.education_questions (
    id bigint generated by default as identity primary key,
    category_id bigint references public.education_categories(id) on delete cascade not null,
    question text not null,
    options jsonb not null, -- Array of strings e.g. ["A", "B", "C", "D"]
    correct_index smallint not null, -- Index of correct answer in options array (0-based)
    difficulty text check (difficulty in ('easy', 'medium', 'hard')) default 'medium',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Education Facts Table
-- Fun Facts (random) and FYI (contextual if needed)
create table if not exists public.education_facts (
    id bigint generated by default as identity primary key,
    category_id bigint references public.education_categories(id) on delete cascade not null,
    content text not null,
    source text, -- Optional source attribution
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.education_categories enable row level security;
alter table public.education_questions enable row level security;
alter table public.education_facts enable row level security;

-- Policies (Public Read)
create policy "Allow public read access to categories"
    on public.education_categories for select
    using (true);

create policy "Allow public read access to questions"
    on public.education_questions for select
    using (true);

create policy "Allow public read access to facts"
    on public.education_facts for select
    using (true);

-- Insert Default Categories
insert into public.education_categories (slug, title)
values 
    ('math', 'Matematika'),
    ('science', 'Ilmu Pengetahuan Alam'),
    ('culture', 'Sosial & Budaya'),
    ('general', 'Pengetahuan Umum')
on conflict (slug) do nothing;
