
-- Insert Questions (50 rows per category = 200 questions total)
INSERT INTO public.education_questions (category_id, question, options, correct_index, difficulty)
VALUES
    -- ==========================================
    -- MATH (50 Questions)
    -- ==========================================
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '2 + 2 x 2 = ?', '["6", "8", "4", "2"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Sudut siku-siku besarnya berapa derajat?', '["45", "90", "180", "120"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Akar kuadrat dari 144 adalah...', '["11", "12", "13", "14"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Bangun datar yang memiliki 3 sisi disebut...', '["Persegi", "Lingkaran", "Segitiga", "Trapesium"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '10 dibagi setengah sama dengan...', '["5", "20", "10", "15"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa hasil dari 5 x 5 + 5?', '["25", "30", "35", "55"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Nilai π (pi) kira-kira adalah...', '["3.14", "3.41", "4.14", "2.14"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Jumlah sudut dalam segitiga adalah...', '["180 derajat", "360 derajat", "90 derajat", "270 derajat"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Angka romawi X bernilai...', '["5", "10", "100", "50"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '1 jam berapa detik?', '["3600", "60", "1200", "7200"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Jika 2x = 10, berapakah x?', '["2", "5", "8", "20"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa sisi yang dimiliki kubus?', '["4", "6", "8", "12"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '1, 1, 2, 3, 5, ..., angka selanjutnya adalah?', '["6", "7", "8", "9"]'::jsonb, 2, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa 15% dari 200?', '["20", "30", "15", "25"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Rumus luas persegi panjang adalah...', '["p x l", "s x s", "a x t", "2(p+l)"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Mana yang merupakan bilangan prima?', '["9", "15", "17", "21"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapakah 7 kuadrat?', '["14", "49", "21", "56"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Kebalikan dari 1/2 adalah...', '["2", "0.2", "-2", "1"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa milenium dalam 2000 tahun?', '["1", "2", "3", "20"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Sudut tumpul besarnya...', '["< 90", "= 90", "> 90 & < 180", "= 180"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '100 - 45 = ?', '["55", "65", "45", "35"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Apa itu hipotenusa?', '["Sisi miring segitiga", "Garis tengah lingkaran", "Tinggi trapesium", "Pusat lingkaran"]'::jsonb, 0, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Hasil dari (-5) x (-6) adalah...', '["-30", "30", "11", "-11"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Bilangan biner untuk 2 adalah...', '["01", "10", "11", "100"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Logaritma basis 10 dari 100 adalah...', '["1", "2", "10", "0"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa volume kubus dengan sisi 3cm?', '["9 cm3", "18 cm3", "27 cm3", "36 cm3"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Keliling lingkaran dengan diameter 10cm adalah (π=3.14)...', '["15.7 cm", "31.4 cm", "78.5 cm", "100 cm"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '1 Lusin berapa buah?', '["10", "12", "20", "24"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '1 Kodi berapa buah?', '["10", "20", "50", "100"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '1 Gros berapa lusin?', '["10", "12", "20", "144"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Bangun ruang yang tidak punya sudut adalah...', '["Kubus", "Bola", "Kerucut", "Limas"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa 1/4 dalam bentuk desimal?', '["0.25", "0.5", "0.75", "0.4"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Alat ukur sudut disebut...', '["Jangka", "Busur", "Penggaris", "Meteran"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Jumlah simetri lipat persegi ada...', '["2", "3", "4", "8"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa hasil 0 dibagi 5?', '["0", "5", "Tak terhingga", "Error"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa hasil 5 dibagi 0?', '["0", "5", "Tak terdefinisi", "1"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Sudut 180 derajat disebut sudut...', '["Lancip", "Siku-siku", "Lurus", "Refleks"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Tiga angka pertama π (pi) adalah...', '["3.12", "3.13", "3.14", "3.15"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Rumus Phytagoras adalah...', '["a+b=c", "a^2+b^2=c^2", "a*b=c", "a/b=c"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa jumlah titik sudut limas segi empat?', '["4", "5", "6", "8"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Apa simbol tak hingga?', '["∞", "Ω", "π", "∑"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Satu abad adalah ... tahun.', '["10", "100", "1000", "50"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Konversi 1 km ke meter.', '["100 m", "1000 m", "10000 m", "10 m"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapakah 2 pangkat 5?', '["10", "25", "32", "64"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Operasi matematika "modulus" mencari...', '["Hasil bagi", "Sisa bagi", "Perkalian", "Pangkat"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Bangun datar segi enam disebut...', '["Pentagon", "Hexagon", "Heptagon", "Octagon"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa 50% dari 50?', '["10", "20", "25", "30"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Urutan operasi hitung yang benar (PEMDAS/Kabataku)...', '["Kali, Bagi, Tambah", "Kurung, Pangkat, Kali/Bagi", "Tambah, Kurang, Kali", "Bebas"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Bilangan ganjil + Bilangan ganjil = Bilangan...', '["Ganjil", "Genap", "Prima", "Nol"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Berapa jari-jari lingkaran jika diameter 20cm?', '["5 cm", "10 cm", "20 cm", "40 cm"]'::jsonb, 1, 'easy'),

    -- ==========================================
    -- SCIENCE (50 Questions)
    -- ==========================================
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Planet terdekat dari Matahari adalah...', '["Venus", "Bumi", "Merkurius", "Mars"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Hewan yang memakan daging disebut...', '["Herbivora", "Karnivora", "Omnivora", "Insektivora"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'H2O adalah rumus kimia untuk...', '["Udara", "Tanah", "Api", "Air"]'::jsonb, 3, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Bagian tumbuhan yang berfungsi menyerap air adalah...', '["Daun", "Batang", "Akar", "Bunga"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Reptil bernapas menggunakan...', '["Insang", "Kulit", "Paru-paru", "Trakea"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Planet terbesar di Tata Surya adalah...', '["Bumi", "Mars", "Jupiter", "Saturnus"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Gas yang kita hirup untuk bernafas adalah...', '["Karbon Dioksida", "Oksigen", "Nitrogen", "Helium"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Hewan amfibi bisa hidup di...', '["Air saja", "Darat saja", "Air dan Darat", "Udara"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Benda langit yang memiliki ekor disebut...', '["Meteor", "Asteroid", "Komet", "Satelit"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Alat untuk mengukur suhu adalah...', '["Barometer", "Termometer", "Anemometer", "Speedometer"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Peristiwa perubahan air menjadi uap disebut...', '["Membeku", "Mencair", "Menguap", "Menyublim"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Pusat tata surya adalah...', '["Bumi", "Bulan", "Matahari", "Bintang"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Tulang terpanjang pada tubuh manusia ada di...', '["Lengan", "Paha", "Punggung", "Jari"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Proses tumbuhan membuat makanan disebut...', '["Respirasi", "Fotosintesis", "Reproduksi", "Digesti"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Logam yang cair pada suhu ruangan adalah...', '["Besi", "Emas", "Raksa", "Perak"]'::jsonb, 2, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Jantung berfungsi untuk...', '["Menyaring darah", "Memompa darah", "Mencerna makanan", "Bernafas"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Bahan bakar utama pesawat terbang adalah...', '["Bensin", "Solar", "Avtur", "Minyak Tanah"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Laba-laba memiliki berapa kaki?', '["4", "6", "8", "10"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Satelit alami Bumi adalah...', '["Matahari", "Bulan", "Mars", "Phobos"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Lapisan ozon melindungi bumi dari sinar...', '["Inframerah", "Ultraviolet", "Gamma", "X-Ray"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Hewan menyusui disebut...', '["Reptil", "Mamalia", "Aves", "Pisces"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Dinosaurus punah karena hantaman...', '["Gunung", "Asteroid", "Bulan", "Matahari"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Warna pelangi ada berapa?', '["5", "6", "7", "8"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Zat hijau daun disebut...', '["Klorofil", "Stomata", "Xilem", "Floem"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Siapa penemu lampu pijar?', '["Einstein", "Newton", "Edison", "Tesla"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Air mendidih pada suhu berapa derajat Celcius?', '["50", "90", "100", "120"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Raja hutan adalah julukan untuk...', '["Harimau", "Singa", "Gajah", "Serigala"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Baterai mengubah energi kimia menjadi energi...', '["Gerak", "Panas", "Listrik", "Cahaya"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Satuan gaya adalah...', '["Watt", "Joule", "Newton", "Pascal"]'::jsonb, 2, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Planet cincin adalah...', '["Jupiter", "Uranus", "Saturnus", "Neptunus"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Mamalia yang bisa terbang adalah...', '["Burung", "Kelelawar", "Penguin", "Ayam"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Bagian mata yang memberi warna disebut...', '["Pupil", "Iris", "Kornea", "Retina"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Penyakit malaria ditularkan oleh...', '["Lalat", "Nyamuk", "Tikus", "Kecoa"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Magnet menarik benda yang terbuat dari...', '["Kayu", "Plastik", "Besi", "Kaca"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Pemanasan global disebabkan oleh efek...', '["Rumah Kaca", "Doppler", "Tyndall", "Bulan"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Vitamin C banyak terdapat pada...', '["Susu", "Nasi", "Jeruk", "Daging"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Ikan bernapas dengan...', '["Paru-paru", "Kulit", "Insang", "Trakea"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Lapisan terluar bumi disebut...', '["Inti", "Mantel", "Kerak", "Atmosfer"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Alat optik untuk melihat benda kecil adalah...', '["Teleskop", "Mikroskop", "Periskop", "Kamera"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Simbol kimia Emas adalah...', '["Fe", "Ag", "Au", "Cu"]'::jsonb, 2, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Hewan tercepat di darat adalah...', '["Singa", "Cheetah", "Kuda", "Rusa"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Bunyi tidak dapat merambat di...', '["Air", "Udara", "Benda padat", "Ruang hampa"]'::jsonb, 3, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Berapa jumlah gigi susu anak-anak?', '["20", "32", "16", "24"]'::jsonb, 0, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Awan yang menurunkan hujan disebut...', '["Cumulus", "Cirrus", "Stratus", "Nimbus"]'::jsonb, 3, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Tumbuhan pemakan serangga...', '["Mawar", "Kantong Semar", "Anggrek", "Melati"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Planet Merah adalah julukan untuk...', '["Venus", "Mars", "Jupiter", "Bumi"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Zat yang tidak memiliki bentuk tetap adalah...', '["Padat", "Cair", "Logam", "Batu"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Satuan arus listrik adalah...', '["Volt", "Ampere", "Ohm", "Watt"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Katak muda disebut...', '["Ulat", "Kecebong", "Pupa", "Jentik"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Waktu yang dibutuhkan bumi mengelilingi matahari...', '["1 hari", "1 bulan", "1 tahun", "1 abad"]'::jsonb, 2, 'medium'),

    -- ==========================================
    -- CULTURE (50 Questions)
    -- ==========================================
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Ibukota negara Indonesia yang baru akan berlokasi di...', '["Jawa Barat", "Kalimantan Timur", "Sumatera Utara", "Sulawesi Selatan"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Rumah adat Gadang berasal dari daerah...', '["Papua", "Sumatera Barat", "Jawa Tengah", "Bali"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Lagu "Indonesia Raya" diciptakan oleh...', '["W.R. Supratman", "Ismail Marzuki", "Cornel Simanjuntak", "Ibu Sud"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Candi Borobudur merupakan candi agama...', '["Hindu", "Buddha", "Konghucu", "Kristen"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Alat musik Angklung berasal dari...', '["Jawa Barat", "Jawa Timur", "Bali", "Madura"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Tari Kecak berasal dari...', '["Bali", "Jawa", "Sumatera", "Kalimantan"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Senjata tradisional Jawa adalah...', '["Rencong", "Keris", "Badik", "Mandau"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Gudeg adalah makanan khas dari...', '["Jakarta", "Yogyakarta", "Bandung", "Solo"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Suku Asmat berasal dari pulau...', '["Kalimantan", "Sulawesi", "Papua", "Sumatera"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Pahlawan wanita dari Jawa Barat...', '["Kartini", "Cut Nyak Dien", "Dewi Sartika", "Fatmawati"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Batik diakui UNESCO sebagai warisan budaya dari...', '["Malaysia", "Indonesia", "Thailand", "Filipina"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Rumah Honai adalah rumah adat...', '["Papua", "Maluku", "NTT", "NTB"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Bahasa persatuan Indonesia adalah...', '["Jawa", "Melayu", "Indonesia", "Sanskerta"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Hari Kemerdekaan Indonesia dirayakan setiap...', '["21 April", "17 Agustus", "1 Juni", "10 November"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Rendang adalah makanan khas...', '["Sumatera Utara", "Sumatera Barat", "Riau", "Jambi"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Pulau Dewata adalah julukan untuk pulau...', '["Jawa", "Bali", "Lombok", "Sumatera"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Monumen Nasional (Monas) ada di...', '["Bandung", "Surabaya", "Jakarta", "Semarang"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Lagu "Gundul-Gundul Pacul" berasal dari...', '["Jawa Tengah", "Jawa Barat", "Jawa Timur", "Jakarta"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Tari Saman berasal dari...', '["Aceh", "Medan", "Padang", "Palembang"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Gunung Bromo terletak di provinsi...', '["Jawa Tengah", "Jawa Timur", "Jawa Barat", "Bali"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Mata uang Indonesia adalah...', '["Dollar", "Ringgit", "Rupiah", "Yen"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Danau Toba terletak di...', '["Sumatera Utara", "Sumatera Barat", "Aceh", "Lampung"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Jembatan Ampera ada di kota...', '["Palembang", "Padang", "Medan", "Jambi"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Presiden ke-3 Indonesia adalah...', '["Soeharto", "B.J. Habibie", "Megawati", "Gus Dur"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Ibukota Jawa Timur adalah...', '["Malang", "Surabaya", "Kediri", "Madiun"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Sumpah Pemuda terjadi pada tanggal...', '["17 Agustus", "28 Oktober", "10 November", "1 Juni"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Lambang negara Indonesia adalah...', '["Macan", "Garuda", "Banteng", "Elang"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Semboyan negara Indonesia...', '["Tut Wuri Handayani", "Bhinneka Tunggal Ika", "Merdeka atau Mati", "Rawe-rawe rantas"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Candi Prambanan bercorak agama...', '["Buddha", "Hindu", "Islam", "Kristen"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Kota Pahlawan adalah julukan kota...', '["Jakarta", "Bandung", "Surabaya", "Semarang"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Pakaian adat Jawa Tengah untuk pria...', '["Kebaya", "Beskap/Jawi Jangkep", "Ulos", "Bodo"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Alat musik Sasando berasal dari...', '["NTT", "NTB", "Maluku", "Papua"]'::jsonb, 0, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Raja Ampat terletak di provinsi...', '["Maluku", "Papua Barat Daya", "Sulawesi", "NTT"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Tari Piring berasal dari...', '["Sumatera Utara", "Sumatera Barat", "Riau", "Jambi"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Ibukota Kalimantan Timur adalah...', '["Balikpapan", "Samarinda", "Bontang", "Pontianak"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Penulis novel "Laskar Pelangi" adalah...', '["Tere Liye", "Andrea Hirata", "Raditya Dika", "Dee Lestari"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Bika Ambon adalah oleh-oleh dari...', '["Ambon", "Medan", "Jakarta", "Bandung"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Hari Kartini diperingati setiap...', '["21 April", "22 Desember", "1 Juni", "2 Mei"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Masjid Istiqlal ada di...', '["Bandung", "Surabaya", "Jakarta", "Semarang"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Suku Dayak berasal dari pulau...', '["Sumatera", "Jawa", "Kalimantan", "Sulawesi"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Badak bercula satu dilindungi di...', '["Ujung Kulon", "Komodo", "Way Kambas", "Baluran"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Kitab Sutasoma dikarang oleh...', '["Empu Prapanca", "Empu Tantular", "Empu Gandring", "Gajah Mada"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Lagu "Apuse" berasal dari...', '["Maluku", "Papua", "Sulawesi", "NTT"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Pahlawan dari Maluku adalah...', '["Pattimura", "Diponegoro", "Imam Bonjol", "Hasanuddin"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Sultan Hasanuddin dijuluki...', '["Ayam Jantan dari Timur", "Singa Podium", "Bapak Koperasi", "Bapak Pendidikan"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Kota Kembang adalah julukan kota...', '["Bogor", "Bandung", "Malang", "Medan"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Pempek berasal dari...', '["Lampung", "Palembang", "Padang", "Bengkulu"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Senjata tradisional Sulawesi Selatan...', '["Badik", "Rencong", "Keris", "Kujang"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Provinsi termuda di Indonesia (per 2024)?', '["Papua Barat Daya", "Papua Tengah", "Papua Pegunungan", "Papua Selatan"]'::jsonb, 0, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Lompat Batu adalah tradisi dari...', '["Nias", "Bali", "Papua", "Toraja"]'::jsonb, 0, 'hard'),

    -- ==========================================
    -- GENERAL (50 Questions)
    -- ==========================================
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Siapakah presiden pertama Indonesia?', '["Soeharto", "B.J. Habibie", "Soekarno", "Jokowi"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Mata uang negara Jepang adalah...', '["Yuan", "Won", "Yen", "Dollar"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Apa warna bendera negara Indonesia?', '["Merah Putih", "Merah Biru", "Putih Merah", "Merah Kuning"]'::jsonb, 0, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Monas terletak di kota...', '["Bandung", "Jakarta", "Surabaya", "Medan"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Tahun berapa Indonesia merdeka?', '["1944", "1945", "1946", "1947"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Benua terbesar di dunia adalah...', '["Afrika", "Eropa", "Asia", "Amerika"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Negara tetangga Indonesia di utara adalah...', '["Australia", "Malaysia", "Jepang", "China"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Bahasa Inggris dari "Buku" adalah...', '["Pen", "Book", "Table", "Chair"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Siapa penemu telepon?', '["Graham Bell", "Edison", "Einstein", "Newton"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Apa nama buah yang identik dengan Isaac Newton?', '["Mangga", "Apel", "Jeruk", "Pisang"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Ibukota negara Jepang adalah...', '["Seoul", "Beijing", "Tokyo", "Bangkok"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Menara Eiffel terletak di negara...', '["Italia", "Prancis", "Jerman", "Inggris"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Binatang yang bisa hidup di darat dan air disebut...', '["Mamalia", "Amfibi", "Reptil", "Unggas"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Matahari terbit dari arah...', '["Barat", "Timur", "Utara", "Selatan"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Olahraga yang menggunakan raket dan kok...', '["Tenis", "Badminton", "Pingpong", "Basket"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Jumlah pemain sepak bola dalam satu tim...', '["9", "10", "11", "12"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Makanan pokok orang Indonesia umumnya...', '["Roti", "Nasi", "Kentang", "Jagung"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Siapa pencipta karakter Mickey Mouse?', '["Walt Disney", "Stan Lee", "JK Rowling", "Dr. Seuss"]'::jsonb, 0, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Patung Liberty ada di negara...', '["Inggris", "Prancis", "Amerika Serikat", "Kanada"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Alat transportasi yang berjalan di atas rel...', '["Bus", "Kereta Api", "Kapal", "Pesawat"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Zodiak berlambang singa adalah...', '["Aries", "Leo", "Taurus", "Gemini"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'CEO Tesla dan SpaceX adalah...', '["Bill Gates", "Jeff Bezos", "Elon Musk", "Mark Zuckerberg"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Aplikasi pesan instan berwarna hijau...', '["Telegram", "WhatsApp", "Line", "Signal"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'YouTube adalah situs berbagi...', '["Foto", "Video", "Musik", "Dokumen"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Ibukota Inggris adalah...', '["Paris", "London", "Berlin", "Roma"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Mata uang Eropa adalah...', '["Dollar", "Pound", "Euro", "Franc"]'::jsonb, 2, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Piala Dunia 2022 diadakan di...', '["Rusia", "Qatar", "Brasil", "Jepang"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Binatang leher panjang...', '["Gajah", "Jerapah", "Rusa", "Kuda"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Raja buah yang berduri...', '["Nangka", "Durian", "Sirsak", "Salak"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Gedung tertinggi di dunia (Burj Khalifa) ada di...', '["Arab Saudi", "Dubai (UEA)", "Qatar", "Kuwait"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Superhero yang takut batu Kryptonite...', '["Batman", "Superman", "Spiderman", "Ironman"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Siapa penulis Harry Potter?', '["J.R.R. Tolkien", "J.K. Rowling", "Stephen King", "Dan Brown"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Logo Apple adalah buah...', '["Jeruk", "Apel", "Pir", "Mangga"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Negara Paman Sam adalah julukan...', '["Inggris", "Rusia", "Amerika Serikat", "China"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Berapa detik dalam satu menit?', '["30", "45", "60", "90"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Google didirikan oleh Larry Page dan...', '["Steve Jobs", "Sergey Brin", "Bill Gates", "Mark Zuckerberg"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Facebook sekarang berganti nama induk menjadi...', '["Alphabet", "Meta", "X", "Social"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Tembok Raksasa ada di negara...', '["Jepang", "China", "Korea", "Mongolia"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Negara Gajah Putih adalah...', '["India", "Thailand", "Vietnam", "Kamboja"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Lukisan Monalisa karya siapa?', '["Picasso", "Da Vinci", "Van Gogh", "Michelangelo"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Titanic tenggelam tahun...', '["1900", "1912", "1920", "1945"]'::jsonb, 1, 'hard'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Samudra terluas di dunia...', '["Hindia", "Pasifik", "Atlantik", "Arktik"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Kangguru hewan khas negara...', '["Austria", "Australia", "Amerika", "Afrika"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Sushi berasal dari...', '["China", "Korea", "Jepang", "Thailand"]'::jsonb, 2, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Pizza berasal dari...', '["Prancis", "Italia", "Spanyol", "Yunani"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Ibundo kota Malaysia...', '["Johor", "Kuala Lumpur", "Penang", "Selangor"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Mata uang Arab Saudi...', '["Dinar", "Riyal", "Dirham", "Lira"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Juara Piala Dunia 2022...', '["Prancis", "Argentina", "Jerman", "Brasil"]'::jsonb, 1, 'medium'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Platform video pendek populer...', '["Instagram", "TikTok", "Snapchat", "Twitter"]'::jsonb, 1, 'easy'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Kartun kucing robot biru dari masa depan...', '["Hattori", "Doraemon", "Conan", "Sinchan"]'::jsonb, 1, 'easy');

-- Insert Facts (Approx 10-15 per category for variety)
INSERT INTO public.education_facts (category_id, content)
VALUES
    -- MATH
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Nol (0) adalah satu-satunya angka yang tidak bisa ditulis dalam angka Romawi.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Di dadu, jumlah angka pada sisi yang berlawanan selalu 7.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Angka 4 di Asia Timur sering dianggap sial karena bunyinya mirip kata "mati".'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), '111.111.111 x 111.111.111 = 12.345.678.987.654.321.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Lebah membangun sarang berbentuk heksagonal karena paling efisien menyimpan madu.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Simbol "=" ditemukan oleh Robert Recorde pada tahun 1557 karena ia bosan menulis "sama dengan".'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Googol adalah angka 1 diikuti oleh 100 nol.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Ada kemungkinan mengocok kartu remi dengan urutan yang belum pernah terjadi sebelumnya dalam sejarah alam semesta.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'math'), 'Pizza dengan jari-jari "z" dan tinggi "a" memiliki volume Pi*z*z*a.'),

    -- SCIENCE
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Jerapah memiliki lidah berwarna biru-hitam.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Satu juta Bumi bisa muat di dalam Matahari.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Udang memiliki jantung di kepalanya.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Gajah adalah satu-satunya mamalia yang tidak bisa melompat.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Air panas dapat membeku lebih cepat daripada air dingin (efek Mpemba).'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Lidah manusia memiliki sidik jari yang unik seperti jari tangan.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Kecoak bisa hidup beberapa minggu tanpa kepala.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Madu tidak pernah basi. Arkeolog menemukan madu di makam Mesir kuno yang masih bisa dimakan.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'DNA manusia dan pisang memiliki kemiripan sekitar 50%.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'science'), 'Venus berputar berlawanan arah dengan Bumi.'),
    
    -- CULTURE
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Indonesia memiliki lebih dari 17.000 pulau.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Bahasa Indonesia berasal dari Bahasa Melayu.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Indomie adalah salah satu mi instan terpopuler di dunia.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Komodo hanya ada di Indonesia secara alami.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Bunga Rafflesia Arnoldii adalah bunga terbesar di dunia dan ada di Bengkulu, Indonesia.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Danau Toba adalah danau vulkanik terbesar di dunia.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Indonesia adalah negara dengan populasi Muslim terbesar di dunia.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Candi Borobudur adalah candi Buddha terbesar di dunia.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Rendang pernah dinobatkan sebagai makanan terenak di dunia oleh CNN.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'culture'), 'Wayang Kulit diakui UNESCO sebagai Warisan Budaya Lisan dan Nonbendawi Manusia.'),

    -- GENERAL
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Cokelat dulu digunakan sebagai mata uang oleh suku Maya.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Rusia memiliki luas permukaan yang lebih besar daripada Pluto.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Nama asli boneka Barbie adalah Barbara Millicent Roberts.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Kaus kaki Albert Einstein jarang cocok karena ia tidak suka memakainya.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Ada lebih banyak bintang di alam semesta daripada butiran pasir di semua pantai di Bumi.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Oxford University lebih tua dari Kekaisaran Aztec.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Prancis adalah negara yang paling banyak dikunjungi turis di dunia.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Bermain catur dapat meningkatkan daya ingat dan konsentrasi.'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Huruf yang paling sering digunakan dalam bahasa Inggris adalah "E".'),
    ((SELECT id FROM public.education_categories WHERE slug = 'general'), 'Ketchup (saus tomat) dulunya dijual sebagai obat pada tahun 1830-an.');
